#!/usr/bin/env bash
# Validate a pull-request branch name: <type>/<kebab-case-description>.
# Dependabot branches (dependabot/...) are exempt: their names are generated.
# Usage: scripts/check_branch_name.sh <branch>
set -euo pipefail

branch="${1:?usage: check_branch_name.sh <branch>}"
types='feat|fix|docs|chore|refactor|test|ci|perf|build|revert'
pattern="^(${types})/[a-z0-9]+(-[a-z0-9]+)*$"

if [[ "$branch" == dependabot/* ]]; then
  echo "Branch '$branch' is generated by Dependabot; skipping."
  exit 0
fi

if [[ "$branch" =~ $pattern ]]; then
  echo "Branch name '$branch' is valid."
  exit 0
fi

echo "Invalid branch name: '$branch'" >&2
echo "Expected <type>/<kebab-case>, type one of: ${types//|/, }" >&2
echo "Example: feat/activity-logs" >&2
exit 1
